---
patterns:
  pattern1:
    grok: "My name is %{WORD:Name} and the age is %{NUMBER:age}"
    match:
      Name: 'VikrantRana'
      age: '26'
  pattern2:
    grok: "My name is %{WORD:Name}"
    match:
      Name: "Bob"